# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e7e3d041f9b4056ba1ab4cd2856e89685bd17fa7992f8894aa8df159a9027f1e6299a524d3731731e34e30d8f78ea3a93c035ec7d5abb280032161a45bb1414

test:
  secret_key_base: 8273966b0fbff1f953c4ae1520c03cdf46fcced99b2f51f38d75767cb7bdd71695fb67f8b6eeb7c4bfd205c89d592bbc6c10e210cbcd5041ae7e3564788bba01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
